version: '3'
services:
  db:
    image: mariadb:10.3
    container_name: drupal_db
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: drupal_phpmyadmin
    restart: always
    ports: 
      - "8082:80"
    environment: 
      # FOR MAX UPLOAD FILE
      UPLOAD_LIMIT: 1G
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 

  drupal:   
    image: drupal:latest
    container_name: drupal 
    depends_on:
      - db
    build: .  
    ports:
      - "8080:80"
      - "2443:443"
    volumes:
      - ./:/var/www/html
    restart: always

  solr:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - ./mycores/collection1:/mycores/collection1
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - collection1
      - /mycores/collection1
volumes:
  db_data:
